# Generated by Django 2.1.1 on 2018-09-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='selling',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
